package com.terryreed.swipelist

import android.content.Context
import org.json.JSONObject

/**
 * Provides a mapping from item names to grocery categories so that pasted
 * lists can be grouped by similar items.
 */
object GroceryCategorizer {
    /** Ordering of categories when sorting items. */
    enum class Category {
        PRODUCE,
        BAKERY,
        MEAT,
        FISH,
        DAIRY,
        EGGS,
        FROZEN,
        DRINKS,
        ALCOHOL,
        HOUSEHOLD,
        BABY,
        PET,
        OTHER
    }

    private val itemCategories = mutableMapOf<String, Category>().apply {
        listOf(
            "apple",
            "apricot",
            "anya",
            "banana",
            "baking potato",
            "baby carrot",
            "baby sweet pepper",
            "berry",
            "beetroot",
            "black kale",
            "broccoli",
            "bunched beetroot",
            "carrot",
            "cavolo nero",
            "celery",
            "cherry",
            "cherry tomato",
            "currant",
            "cucumber",
            "fig",
            "fresh herb",
            "fresh salad bag",
            "grape",
            "heritage tomato",
            "kale",
            "kiwi",
            "lemon",
            "lettuce",
            "lychee",
            "mango",
            "medjool date",
            "melon",
            "mushroom",
            "nectarine",
            "onion",
            "orange",
            "oyster mushroom",
            "papaya",
            "peach",
            "pear",
            "pineapple",
            "plum",
            "plum tomato",
            "pomegranate",
            "potato",
            "purple sprouting broccoli",
            "raspberry",
            "ready to eat fruit mix",
            "red sweet pointed pepper",
            "shiitake",
            "shredded beetroot",
            "speciality mushroom",
            "spinach",
            "stir fry vegetable mix",
            "strawberry",
            "sweet carrot",
            "sweet onion",
            "tenderstem",
            "tomato",
            "vine tomato",
            "vivaldi salad potato"
        ).forEach { put(it, Category.PRODUCE) }
        listOf(
            "bread",
            "bread roll",
            "roll",
            "loaf",
            "white loaf",
            "wholemeal loaf",
            "sourdough loaf",
            "bap",
            "baguette",
            "ciabatta",
            "sandwich slice",
            "flatbread",
            "bagel",
            "crumpet",
            "muffin",
            "doughnut",
            "scone",
            "cupcake",
            "traybake",
            "bar cookie",
            "drop cookie",
            "rolled cookie",
            "biscuit",
            "bourbon biscuit",
            "shortbread",
            "rich tea",
            "digestive",
            "custard cream",
            "hobnob",
            "jaffa cake",
            "flapjack",
            "brownie",
            "pastry",
            "pasty",
            "sausage roll",
            "steak pie",
            "tart",
            "teacake",
            "welsh cake",
            "gur cake",
            "flies graveyard",
            "sticky toffee pudding",
            "dessert cake",
            "sponge cake",
            "tiered cake",
            "wedding cake",
            "cookie",
            "croissant",
            "pita",
            "pain au chocolat",
            "puff pastry",
            "eclair",
            "danish pastry",
            "bun",
            "pretzel",
            "artisan bread",
            "sheet cake",
            "layer cake"
        ).forEach { put(it, Category.BAKERY) }
        listOf(
            "back bacon",
            "bacon",
            "bacon rashers",
            "beef",
            "beef brisket",
            "beef burgers",
            "beef mince",
            "beef ribs",
            "beef roasting joint",
            "beef steaks",
            "chicken",
            "chicken breasts",
            "chicken drumsticks",
            "chicken mince",
            "chicken thighs",
            "chicken wings",
            "duck breast",
            "duck legs",
            "gammon joint",
            "goat meat",
            "goose breast",
            "goose leg",
            "ham",
            "ham joint",
            "ham slices",
            "lamb",
            "lamb chops",
            "lamb leg joint",
            "lamb mince",
            "lamb shank",
            "pork",
            "pork belly",
            "pork chops",
            "pork loin",
            "pork mince",
            "pork ribs",
            "pork sausages",
            "rabbit meat",
            "streaky bacon",
            "turkey breast",
            "turkey mince",
            "turkey steaks",
            "venison mince",
            "venison sausages",
            "venison steaks",
            "whole chicken",
            "whole duck",
            "whole goose"
        ).forEach { put(it, Category.MEAT) }
        listOf(
            "anchovies",
            "calamari",
            "clams",
            "cod",
            "cod fillets",
            "crab",
            "crab meat",
            "fish fingers",
            "haddock",
            "haddock fillets",
            "hake",
            "hake fillets",
            "halibut",
            "halibut steaks",
            "jumbo prawns",
            "kippers",
            "king prawns",
            "lobster",
            "mackerel",
            "mackerel fillets",
            "monkfish",
            "monkfish fillets",
            "mussels",
            "octopus",
            "oysters",
            "plaice",
            "plaice fillets",
            "pollock",
            "pollock fillets",
            "prawns",
            "prawns cooked",
            "prawns peeled",
            "prawns raw",
            "salmon",
            "salmon fillets",
            "sardines",
            "scampi",
            "sea bass",
            "sea bass fillets",
            "seafood mix",
            "smoked mackerel",
            "smoked salmon",
            "sole",
            "sole fillets",
            "squid",
            "squid rings",
            "trout",
            "trout fillets",
            "tuna",
            "tuna steaks"
        ).forEach { put(it, Category.FISH) }
        listOf(
            "activia",
            "almond milk",
            "alpro",
            "ambrosia custard",
            "ambrosia rice pudding",
            "anchor butter",
            "arla cravendale",
            "babybel",
            "blue cheese",
            "brie",
            "camembert",
            "butter",
            "cathedral city",
            "cheddar",
            "cheese",
            "cheshire cheese",
            "clotted cream",
            "coconut milk (dairy alternative)",
            "country life butter",
            "cream",
            "cream cheese",
            "cottage cheese",
            "crème fraîche",
            "custard",
            "dairylea",
            "double gloucester",
            "double cream",
            "elmlea",
            "feta",
            "flavoured yogurt",
            "flora",
            "frijj",
            "greek yogurt",
            "halloumi",
            "kerrygold",
            "lactose free milk",
            "lancashire cheese",
            "laughing cow",
            "mature cheddar",
            "long life milk",
            "low fat yogurt",
            "lurpak",
            "margarine",
            "mars milkshake",
            "milk",
            "milkshake",
            "mild cheddar",
            "mozzarella",
            "müller corner",
            "natural yogurt",
            "nesquik milkshake",
            "oat milk",
            "oatly",
            "onken",
            "parmesan",
            "philadelphia",
            "pilgrims choice",
            "red leicester",
            "rice pudding",
            "salted butter",
            "semi skimmed milk",
            "single cream",
            "skimmed milk",
            "uht milk",
            "skyr",
            "soft cheese",
            "sour cream",
            "soya milk",
            "stilton",
            "unsalted butter",
            "vitalite",
            "whipping cream",
            "whole milk",
            "yeo valley",
            "yogurt",
            "yazoo",
            "wensleydale"
        ).forEach { put(it, Category.DAIRY) }
        listOf(
            "egg",
            "eggs",
            "free range eggs",
            "organic eggs",
            "duck eggs",
            "quail eggs"
        ).forEach { put(it, Category.EGGS) }
        listOf(
            "ice cream",
            "frozen peas",
            "frozen pizza",
            "chips",
            "frozen vegetables",
            "frozen sweetcorn",
            "frozen broccoli florets",
            "frozen mixed vegetables",
            "frozen green beans",
            "frozen spinach",
            "frozen cauliflower",
            "frozen carrots",
            "frozen herbs",
            "frozen blueberries",
            "frozen raspberries",
            "frozen black forest fruits",
            "frozen summer fruits",
            "frozen mango chunks",
            "frozen pineapple pieces",
            "frozen strawberries",
            "frozen chicken breasts",
            "frozen chicken thighs",
            "frozen chicken nuggets",
            "frozen chicken dippers",
            "frozen chicken kievs",
            "frozen turkey breast",
            "frozen turkey burgers",
            "frozen pork sausages",
            "frozen beef sausages",
            "frozen chicken sausages",
            "frozen beef burgers",
            "frozen minced beef",
            "frozen meatballs",
            "frozen lamb chops",
            "frozen pork chops",
            "frozen cod fillets",
            "frozen haddock fillets",
            "frozen salmon fillets",
            "frozen fish fingers",
            "frozen breaded fish fillets",
            "frozen battered fish fillets",
            "frozen jumbo king prawns",
            "frozen raw prawns",
            "frozen cooked prawns",
            "frozen peeled prawns",
            "frozen scampi",
            "frozen seafood mix",
            "frozen lasagne",
            "frozen cottage pie",
            "frozen shepherd's pie",
            "frozen spaghetti bolognese",
            "frozen macaroni cheese",
            "frozen chicken curry",
            "frozen beef curry",
            "frozen thai curry",
            "frozen chinese meal",
            "frozen stir-fry meal",
            "frozen deep-dish pizza",
            "frozen stone-baked pizza",
            "frozen stuffed crust pizza",
            "frozen quiche",
            "frozen sausage rolls",
            "frozen mini pies",
            "frozen spring rolls",
            "frozen samosas",
            "frozen party platter",
            "frozen crinkle chips",
            "frozen straight-cut chips",
            "frozen oven chips",
            "frozen steak-cut chips",
            "frozen curly fries",
            "frozen potato wedges",
            "frozen hash browns",
            "frozen potato waffles",
            "frozen jacket potatoes",
            "frozen roast potatoes",
            "frozen croissants",
            "frozen all-butter croissants",
            "frozen pain au chocolat",
            "frozen waffles",
            "frozen pancakes",
            "frozen yorkshire puddings",
            "frozen garlic bread",
            "frozen naan bread",
            "frozen parathas",
            "ice cream tubs",
            "ice cream cones",
            "ice lollies",
            "choc ices",
            "frozen cheesecakes",
            "profiteroles",
            "gateaux",
            "roulades",
            "carte d'or",
            "haagen-dazs",
            "ben & jerry's",
            "cornetto",
            "calippo",
            "rocket lollies",
            "twister"
        ).forEach { put(it, Category.FROZEN) }
        listOf(
            "water",
            "juice",
            "soda",
            "tea",
            "coffee",
            "coca-cola",
            "diet coke",
            "coca-cola zero sugar",
            "pepsi",
            "pepsi max",
            "pepsi diet",
            "virgin cola",
            "tesco cola",
            "sainsbury's cola",
            "asda cola",
            "lidl cola",
            "fanta orange",
            "fanta fruit twist",
            "fanta lemon",
            "tango orange",
            "tango apple",
            "tango dark berry",
            "7up",
            "7up free",
            "sprite",
            "irn-bru",
            "fanta pineapple & grapefruit",
            "dr pepper",
            "mountain dew",
            "ka caribbean drinks",
            "rubicon mango",
            "rubicon guava",
            "rubicon lychee",
            "schweppes lemonade",
            "r. white's lemonade",
            "fever-tree lemonade",
            "schweppes ginger ale",
            "fever-tree ginger beer",
            "old jamaica ginger beer",
            "barr dandelion & burdock",
            "barr cream soda",
            "shandy bass",
            "red bull",
            "red bull sugarfree",
            "monster energy",
            "monster ultra",
            "relentless",
            "rockstar energy",
            "boost energy",
            "emerge",
            "lucozade energy",
            "lucozade sport",
            "powerade",
            "tropicana orange juice",
            "tropicana apple juice",
            "tropicana mango juice",
            "tropicana multivitamin",
            "innocent orange juice",
            "innocent apple juice",
            "innocent smoothies",
            "copella apple juice",
            "supermarket own-brand juices",
            "j2o orange & passionfruit",
            "j2o apple & mango",
            "j2o apple & raspberry",
            "capri-sun orange",
            "capri-sun summer berries",
            "ribena blackcurrant",
            "ribena raspberry",
            "ribena strawberry",
            "robinsons orange squash",
            "robinsons apple & blackcurrant squash",
            "robinsons summer fruits squash",
            "ribena squash",
            "vimto cordial",
            "supermarket own-brand squash",
            "rocks organic squash",
            "evian",
            "volvic",
            "highland spring",
            "buxton",
            "harrogate spring water",
            "smartwater",
            "aqua pura",
            "supermarket own-brand still water",
            "supermarket own-brand sparkling water",
            "volvic touch of fruit",
            "perfectly clear flavoured water",
            "lipton ice tea peach",
            "lipton ice tea lemon",
            "lipton ice tea mango",
            "arizona iced tea",
            "nestea",
            "fuze tea",
            "starbucks chilled coffee",
            "costa chilled coffee",
            "innocent bubbles",
            "vitamin water",
            "purdey's",
            "aqua libra",
            "coke",
            "zero sugar coke",
            "orange soda",
            "lemon soda",
            "apple soda",
            "berry soda",
            "tropical fruit soda",
            "mixed fruit soda",
            "lemonade",
            "cloudy lemonade",
            "ginger beer",
            "ginger ale",
            "dandelion and burdock",
            "cream soda",
            "shandy",
            "energy drinks",
            "sugar-free energy drinks",
            "sports drinks",
            "isotonic drinks",
            "electrolyte drinks",
            "orange juice",
            "apple juice",
            "tropical juice",
            "mango juice",
            "multivitamin juice",
            "mixed fruit juice",
            "fruit smoothies",
            "fruit juice blends",
            "long-life fruit juice",
            "orange squash",
            "blackcurrant squash",
            "summer fruits squash",
            "tropical squash",
            "no-added-sugar squash",
            "cordial",
            "still water",
            "sparkling water",
            "flavoured still water",
            "flavoured sparkling water",
            "functional water",
            "iced tea",
            "sparkling fruit drinks",
            "sparkling tea",
            "iced coffee",
            "malted drinks",
            "hot chocolate (ready to drink)",
            "prebiotic drinks"
        ).forEach { put(it, Category.DRINKS) }
        listOf(
            // Beers & ales
            "beer", "lager", "carling", "fosters", "stella artois", "carlsberg",
            "heineken", "budweiser", "amstel", "kronenbourg 1664", "san miguel",
            "peroni", "birra moretti", "corona", "guinness", "john smith's",
            "hobgoblin", "newcastle brown ale", "ale", "bitter", "ipa", "craft beer",
            // Cider
            "cider", "strongbow", "strongbow dark fruit", "bulmers", "magners",
            "thatchers", "kopparberg", "rekorderlig", "old mout", "westons",
            "scrumpy cider",
            // Wine
            "wine", "red wine", "white wine", "rosé wine", "sparkling wine",
            "champagne", "prosecco", "cava", "merlot", "cabernet sauvignon", "shiraz",
            "malbec", "pinot noir", "chardonnay", "sauvignon blanc",
            "pinot grigio", "riesling", "zinfandel",
            // Fortified & others
            "sherry", "port", "vermouth",
            // Whiskey
            "whiskey", "whisky", "scotch whisky", "irish whiskey", "bourbon",
            "jack daniel's", "jameson", "johnnie walker", "glenfiddich",
            "the macallan", "famous grouse", "bells",
            // Vodka
            "vodka", "smirnoff", "absolut", "grey goose", "ciroc",
            // Rum
            "rum", "bacardi", "captain morgan", "malibu", "havana club",
            "kraken",
            // Gin
            "gin", "gordon's", "bombay sapphire", "tanqueray", "beefeater",
            "hendrick's",
            // Tequila & mezcal
            "tequila", "jose cuervo", "patrón", "mezcal",
            // Brandy & cognac
            "brandy", "cognac", "hennessy", "courvoisier", "rémy martin",
            // Liqueurs
            "liqueur", "baileys", "amaretto", "disaronno", "sambuca", "tia maria",
            "kahlua", "cointreau", "grand marnier", "aperol", "campari",
            "jägermeister", "pimm's",
            // Alcopops & seltzers
            "alcopops", "wkd", "smirnoff ice", "bacardi breezer", "hard seltzer",
            "white claw", "truly"
        ).forEach { put(it, Category.ALCOHOL) }
        listOf(
            "toilet paper",
            "bleach",
            "laundry detergent",
            "dish soap",
            "bin bag",
            "cleaner",
            "toilet roll",
            "kitchen roll",
            "tissues",
            "hand soap",
            "shower gel",
            "shampoo",
            "conditioner",
            "toothpaste",
            "toothbrush",
            "mouthwash",
            "dental floss",
            "deodorant",
            "razors",
            "shaving foam",
            "cotton buds",
            "cotton pads",
            "plasters",
            "first aid kit",
            "painkillers",
            "washing powder",
            "washing liquid",
            "fabric conditioner",
            "stain remover",
            "laundry capsules",
            "disinfectant",
            "multipurpose cleaner",
            "bathroom cleaner",
            "kitchen cleaner",
            "floor cleaner",
            "washing up liquid",
            "dishwasher tablets",
            "dishwasher salt",
            "sponges",
            "cloths",
            "scourers",
            "bin bags",
            "food bags",
            "sandwich bags",
            "cling film",
            "tin foil",
            "baking paper",
            "freezer bags",
            "storage boxes",
            "matches",
            "lighters",
            "candles",
            "light bulbs",
            "batteries",
            "extension leads",
            "fuses",
            "toilet cleaner",
            "air freshener",
            "furniture polish",
            "glass cleaner",
            "mop",
            "bucket",
            "broom",
            "dustpan and brush",
            "hoover bags",
            "ironing board",
            "iron",
            "pegs",
            "clothes airer",
            "laundry basket",
            "sewing kit",
            "shoe polish",
            "doormat",
            "coat hangers"
        ).forEach { put(it, Category.HOUSEHOLD) }
        listOf(
            "nappies",
            "baby wipes",
            "formula",
            "baby food",
            "baby food pouches",
            "baby food jars",
            "baby fruit pots",
            "baby snacks",
            "cotton wool pads",
            "baby shampoo",
            "baby bath wash",
            "baby lotion",
            "baby oil",
            "baby powder",
            "baby nappy cream",
            "baby massage oil",
            "teething gel",
            "baby washcloths",
            "baby towels",
            "baby bibs",
            "baby feeding bottles",
            "bottle teats",
            "steriliser liquid",
            "steriliser tablets",
            "bottle brushes",
            "nursing pads",
            "breast pads",
            "nipple cream",
            "nursing bras",
            "baby feeding bibs",
            "baby changing mats",
            "disposable changing pads",
            "baby nappy sacks",
            "baby cotton wool",
            "baby cleansing cloths",
            "baby toiletries",
            "gentle baby laundry detergent",
            "baby-friendly toothpaste & toothbrush",
            "baby hairbrush",
            "baby bath thermometer",
            "reusable baby wipes",
            "baby bum cream",
            "baby sun cream",
            "baby skincare products"
        ).forEach { put(it, Category.BABY) }
        listOf(
            "dog food",
            "dry dog food",
            "wet dog food",
            "puppy food",
            "senior dog food",
            "grain free dog food",
            "pedigree",
            "bakers",
            "winalot",
            "chappie",
            "harringtons",
            "james wellbeloved",
            "royal canin",
            "purina beta",
            "iams for dogs",
            "cesar",
            "lily's kitchen dog food",
            "dog treats",
            "dog chews",
            "dentastix",
            "rawhide chews",
            "dog biscuits",
            "training treats",
            "dog toys",
            "dog leads",
            "dog collars",
            "dog harnesses",
            "dog beds",
            "dog blankets",
            "dog shampoo",
            "dog grooming brushes",
            "dog flea treatment",
            "dog worming tablets",
            "dog poop bags",
            "dog bowls",
            "cat food",
            "dry cat food",
            "wet cat food",
            "kitten food",
            "senior cat food",
            "grain free cat food",
            "felix",
            "whiskas",
            "sheba",
            "gourmet cat food",
            "purina one",
            "go-cat",
            "iams for cats",
            "royal canin cat food",
            "james wellbeloved cat food",
            "lily's kitchen cat food",
            "applaws cat food",
            "cat treats",
            "dreamies",
            "catnip",
            "cat litter",
            "clumping cat litter",
            "non clumping cat litter",
            "wood pellet cat litter",
            "cat litter tray",
            "cat scratching post",
            "cat toys",
            "cat bowls",
            "rabbit food",
            "guinea pig food",
            "hamster food",
            "gerbil food",
            "ferret food",
            "bird seed",
            "budgie food",
            "parrot food",
            "wild bird seed",
            "suet balls",
            "fish food",
            "goldfish flakes",
            "tropical fish flakes",
            "pond sticks",
            "reptile food",
            "hay",
            "straw",
            "small animal bedding",
            "sawdust",
            "pet carriers",
            "flea treatment",
            "worming treatment",
            "pet cleaning spray",
            "pet disinfectant"
        ).forEach { put(it, Category.PET) }
    }

    private const val PREFS_NAME = "keyword_prefs"
    private const val KEY_MAPPINGS = "keyword_mappings"

    private val customKeywords: MutableMap<String, Category> = mutableMapOf()
    private var loadedCustomKeywords: Boolean = false

    /** Loads persisted custom keywords from [SharedPreferences]. */
    fun loadCustomKeywords(context: Context) {
        if (loadedCustomKeywords) return
        loadedCustomKeywords = true
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val stored = prefs.getString(KEY_MAPPINGS, null) ?: return
        val json = JSONObject(stored)
        val keys = json.keys()
        while (keys.hasNext()) {
            val keyword = keys.next()
            val categoryName = json.optString(keyword, null) ?: continue
            val category = runCatching { Category.valueOf(categoryName) }.getOrNull() ?: continue
            customKeywords[keyword] = category
            itemCategories[keyword] = category
        }
    }

    private fun persistCustomKeywords(context: Context) {
        val json = JSONObject()
        customKeywords.forEach { (keyword, category) ->
            json.put(keyword, category.name)
        }
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().putString(KEY_MAPPINGS, json.toString()).apply()
    }

    /** Adds [keywords] as mappings for the provided [category]. */
    fun addKeywords(category: Category, keywords: List<String>, context: Context? = null) {
        val normalized = keywords.map { it.trim().lowercase() }.filter { it.isNotEmpty() }
        if (normalized.isEmpty()) return
        normalized.forEach {
            itemCategories[it] = category
            customKeywords[it] = category
        }
        context?.let { persistCustomKeywords(it) }
    }

    /** Removes [keyword] from the provided [category] if present. */
    fun removeKeyword(category: Category, keyword: String, context: Context? = null) {
        val normalized = keyword.trim().lowercase()
        if (itemCategories[normalized] == category) {
            itemCategories.remove(normalized)
            customKeywords.remove(normalized)
            context?.let { persistCustomKeywords(it) }
        }
    }

    /** Returns all keywords currently associated with [category]. */
    fun keywordsFor(category: Category): List<String> =
        itemCategories.filterValues { it == category }.keys.sorted()

    /** Returns the [Category] associated with a given item name. */
    fun categoryFor(name: String): Category {
        val normalized = name.trim().lowercase()
        itemCategories[normalized]?.let { return it }
        return itemCategories.entries.firstOrNull { (key, _) ->
            normalized.contains(key)
        }?.value ?: Category.OTHER
    }

    /** Groups a list of item names by their [Category]. */
    fun groupByCategory(names: List<String>): Map<Category, List<String>> =
        names.groupBy { categoryFor(it) }

    /**
     * Sorts [items] according to the provided [order] of [Category]s.
     */
    fun sortByCategory(
        items: List<ShoppingItem>,
        order: List<Category>
    ): List<ShoppingItem> = items.sortedWith(
        compareBy<ShoppingItem> { order.indexOf(categoryFor(it.name)) }
            .thenBy { it.name.lowercase() }
    )
}
